version: '3'

services:
  mediaserver:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: feixiao/mediaserver:1.0
    container_name: mediaserver
    # ports:
    #   - "10000:22"
    #   - "10001-10010:10001-10010"
    volumes:
      - /home/frank/research/MediaServer:/home/frank/research/MediaServer
    # working_dir: /home/debugger/code
    # hostname: debug



    