version: '3'

services:
  gdbserver:
    build:
    
      context: ./
      dockerfile: ./Dockerfile
    image: janus_build:1.0
    container_name: janus_build
    ports:
      - "2224:22"
      - "7777:7777"
    volumes:
      - .:/home/frank/code
    working_dir: /home/frank/code
    hostname: janus_build

